"""Review-added scholarship sources: RedTeam batch + 2026-06-10 external-review batch (pure data)."""

from __future__ import annotations

from typing import Any

_REDTEAM_REVIEW_SOURCES: tuple[dict[str, Any], ...] = (
    {
        "citation_key": "oh2026vopd",
        "source_kind": "primary_preprint",
        "source_family": "opd_stabilization",
        "method_role": "control_variate_on_policy_distillation",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["methods_sheaf", "discussion_outlook"],
        "claim_boundary": "OPD variance-reduction context only; no vOPD benchmark is reproduced",
    },
    {
        "citation_key": "xing2026tropd",
        "source_kind": "primary_preprint",
        "source_family": "opd_stabilization",
        "method_role": "trust_region_on_policy_distillation",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["methods_sheaf", "discussion_outlook"],
        "claim_boundary": "trust-region OPD context only; local KL geometry remains a toy artifact",
    },
    {
        "citation_key": "jang2026veto",
        "source_kind": "primary_preprint",
        "source_family": "opd_stabilization",
        "method_role": "adaptive_target_reformulation",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["methods_sheaf", "discussion_outlook"],
        "claim_boundary": "adaptive target-stabilization context only",
    },
    {
        "citation_key": "ye2025blackbox_opd",
        "source_kind": "primary_preprint",
        "source_family": "opd_stabilization",
        "method_role": "black_box_on_policy_distillation",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["methods_sheaf", "discussion_outlook"],
        "claim_boundary": "black-box OPD context only; this project uses generated toy teacher scores",
    },
    {
        "citation_key": "champion2024efe_unification",
        "source_kind": "primary_preprint",
        "source_family": "efe_decomposition",
        "method_role": "efe_bayesian_model_evaluation_unification",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/energy_demo.json",
        "manuscript_sections": ["methods_analytical", "methods_pymdp"],
        "claim_boundary": "EFE decomposition context only; local energy values are generated artifacts",
    },
    {
        "citation_key": "sajid2021bayesian_design",
        "source_kind": "primary_preprint",
        "source_family": "efe_decomposition",
        "method_role": "bayesian_optimal_design_expected_utility",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/energy_demo.json",
        "manuscript_sections": ["methods_analytical", "methods_pymdp"],
        "claim_boundary": "Bayesian design and expected-utility context only",
    },
    {
        "citation_key": "devries2025efe_planning_vi",
        "source_kind": "primary_preprint",
        "source_family": "efe_decomposition",
        "method_role": "planning_as_variational_inference",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/energy_demo.json",
        "manuscript_sections": ["methods_analytical", "methods_pymdp"],
        "claim_boundary": "planning-as-VI context only; no planner benchmark is reproduced",
    },
    {
        "citation_key": "odonoghue2020rl_prob_inference",
        "source_kind": "primary_conference",
        "source_family": "rl_as_inference_caveats",
        "method_role": "probabilistic_inference_rl_caveat",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/reward_tilting_demo.json",
        "manuscript_sections": ["methods_analytical", "discussion_outlook"],
        "claim_boundary": "RL-as-inference caveat only; reward-tilt rows are finite generated checks",
    },
    {
        "citation_key": "millidge2020iterative_amortised",
        "source_kind": "primary_preprint",
        "source_family": "rl_as_inference_caveats",
        "method_role": "iterative_amortised_inference_rl_bridge",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/reward_tilting_demo.json",
        "manuscript_sections": ["methods_analytical", "discussion_outlook"],
        "claim_boundary": "iterative/amortised inference bridge only",
    },
    {
        "citation_key": "tschantz2020rl_active_inference",
        "source_kind": "primary_preprint",
        "source_family": "rl_as_inference_caveats",
        "method_role": "rl_through_active_inference",
        "tracks": ["pymdp", "scholarship"],
        "artifact": "output/data/si_tmaze_summary.json",
        "manuscript_sections": ["methods_pymdp", "discussion_outlook"],
        "claim_boundary": "RL-through-active-inference context only; local SI rollout supplies measured evidence",
    },
    {
        "citation_key": "rohatgi2025next_token_barrier",
        "source_kind": "primary_preprint",
        "source_family": "imitation_exposure_bias_lineage",
        "method_role": "next_token_misspecification_barrier",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/exposure_bias_demo.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "misspecification theory context only; not evidence for local toy values",
    },
    {
        "citation_key": "sun2017aggrevated",
        "source_kind": "primary_conference",
        "source_family": "imitation_exposure_bias_lineage",
        "method_role": "differentiable_interactive_imitation",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/exposure_bias_demo.json",
        "manuscript_sections": ["intro_motivation", "methods_pymdp"],
        "claim_boundary": "interactive-imitation lineage only; no robotics/control experiment is reproduced",
    },
    {
        "citation_key": "cai2024privileged_pomdp",
        "source_kind": "primary_preprint",
        "source_family": "privileged_information",
        "method_role": "privileged_sensing_pomdp_scaffold",
        "tracks": ["pymdp", "scholarship"],
        "artifact": "output/data/si_tmaze_summary.json",
        "manuscript_sections": ["methods_pymdp", "results_si_tmaze"],
        "claim_boundary": "privileged-sensing POMDP context only; the T-maze cue remains a toy channel",
    },
    {
        "citation_key": "stanton2021kd_work",
        "source_kind": "primary_conference",
        "source_family": "knowledge_distillation_caveats",
        "method_role": "student_teacher_fidelity_caveat",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["methods_sheaf", "discussion_outlook"],
        "claim_boundary": "KD fidelity caveat only; not a reproduced generalization result",
    },
    {
        "citation_key": "robinson2017sensor_sheaf",
        "source_kind": "primary_article",
        "source_family": "applied_sheaf_integration",
        "method_role": "sensor_sheaf_data_integration",
        "tracks": ["prose", "formalism", "scholarship"],
        "artifact": "output/data/sheaf_gluing_certificate.json",
        "manuscript_sections": ["methods_sheaf", "appendix_full_sheaf"],
        "claim_boundary": "applied local/global integration analogy only",
    },
    {
        "citation_key": "cox2026fragmented_risk_sheaf",
        "source_kind": "primary_article",
        "source_family": "applied_sheaf_integration",
        "method_role": "fragmented_risk_evidence_integration",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/sheaf_gluing_certificate.json",
        "manuscript_sections": ["methods_sheaf", "appendix_full_sheaf"],
        "claim_boundary": "evidence-integration analogy only; not a risk-assessment result here",
    },
    {
        "citation_key": "phillips2019sheaving",
        "source_kind": "primary_article",
        "source_family": "applied_sheaf_integration",
        "method_role": "semantic_compositionality_sheaving",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/sheaf_gluing_certificate.json",
        "manuscript_sections": ["methods_sheaf", "appendix_full_sheaf"],
        "claim_boundary": "semantic-compositionality context only",
    },
    {
        "citation_key": "fong2019applied_category",
        "source_kind": "monograph",
        "source_family": "applied_category_theory",
        "method_role": "compositionality_category_theory_background",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/sheaf_gluing_certificate.json",
        "manuscript_sections": ["methods_sheaf", "appendix_full_sheaf"],
        "claim_boundary": "compositionality background only; local sheaf laws are finite gates",
    },
    {
        "citation_key": "rosiak2022sheaf_examples",
        "source_kind": "monograph",
        "source_family": "applied_sheaf_integration",
        "method_role": "worked_sheaf_examples_background",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/sheaf_gluing_certificate.json",
        "manuscript_sections": ["methods_sheaf", "appendix_full_sheaf"],
        "claim_boundary": "worked-example background only; no cohomology claim is made",
    },
    {
        "citation_key": "friston2021interesting_observations",
        "source_kind": "primary_article",
        "source_family": "fep_scope_debate",
        "method_role": "fep_scope_observations",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/correspondence_map.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "FEP scope context only; local claims stay finite and toy",
    },
    {
        "citation_key": "aguilera2022particular_fep",
        "source_kind": "primary_article",
        "source_family": "fep_scope_debate",
        "method_role": "particularity_of_fep_physics_caveat",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/correspondence_map.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "FEP scope caveat only; avoids biological overclaiming",
    },
    {
        "citation_key": "parr2020markov_blankets_thermo",
        "source_kind": "primary_article",
        "source_family": "fep_markov_blanket",
        "method_role": "markov_blanket_thermodynamic_context",
        "tracks": ["pymdp", "scholarship"],
        "artifact": "output/data/firstprinciples/correspondence_map.json",
        "manuscript_sections": ["methods_pymdp", "results_invariants"],
        "claim_boundary": "Markov-blanket thermodynamics context only; the manuscript uses an informational boundary",
    },
    {
        "citation_key": "wu2024rethinking_kl_kd",
        "source_kind": "primary_preprint",
        "source_family": "kl_geometry_caveats",
        "method_role": "kl_direction_choice_caveat",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["methods_analytical", "discussion_outlook"],
        "claim_boundary": "KL-direction caveat only; local divergence values are generated",
    },
    {
        "citation_key": "ko2025distillm2",
        "source_kind": "primary_preprint",
        "source_family": "kl_geometry_caveats",
        "method_role": "contrastive_distillation_objective",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["methods_analytical", "discussion_outlook"],
        "claim_boundary": "contrastive distillation context only; no DistiLLM-2 metric is reproduced",
    },
    {
        "citation_key": "vanoostrum2024discrete_active_inference",
        "source_kind": "primary_preprint",
        "source_family": "discrete_state_space_active_inference",
        "method_role": "discrete_time_active_inference_notation",
        "tracks": ["pymdp", "formalism", "scholarship"],
        "artifact": "output/data/si_tmaze_summary.json",
        "manuscript_sections": ["methods_pymdp", "methods_analytical"],
        "claim_boundary": "discrete-time active-inference notation only; local SI values are generated",
    },
    {
        "citation_key": "snell2022context_distillation",
        "source_kind": "primary_preprint",
        "source_family": "context_privileged_opd",
        "method_role": "language_model_context_distillation_precedent",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/correspondence_map.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "context-distillation precedent only; no LM result is reproduced",
    },
    {
        "citation_key": "ye2026context_distillation",
        "source_kind": "primary_preprint",
        "source_family": "context_privileged_opd",
        "method_role": "on_policy_context_distillation",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["intro_motivation", "methods_sheaf", "discussion_outlook"],
        "claim_boundary": "privileged context OPD context only; local teacher/student rows remain toy artifacts",
    },
    {
        "citation_key": "lazaridis2026edge_opd",
        "source_kind": "primary_preprint",
        "source_family": "context_privileged_opd",
        "method_role": "evidence_localized_privileged_context",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "privilege-localization caveat only; no rare-token benchmark is reproduced",
    },
    {
        "citation_key": "li2026rethinking_opd",
        "source_kind": "primary_preprint",
        "source_family": "opd_stabilization",
        "method_role": "teacher_student_compatibility_conditions",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "OPD compatibility and mechanism context only; not a reproduced benchmark",
    },
    {
        "citation_key": "luo2026demystifying_opd",
        "source_kind": "primary_preprint",
        "source_family": "opd_stabilization",
        "method_role": "length_inflation_failure_mode",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "length-inflation failure-mode context only",
    },
    {
        "citation_key": "han2026adaptive_teacher_exposure",
        "source_kind": "primary_preprint",
        "source_family": "context_privileged_opd",
        "method_role": "adaptive_teacher_exposure_privilege_schedule",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/classroom.json",
        "manuscript_sections": ["results_si_tmaze", "discussion_outlook"],
        "claim_boundary": "teacher-exposure scheduling context only; classroom entropy values remain local",
    },
    {
        "citation_key": "chen2026freshness_opd",
        "source_kind": "primary_preprint",
        "source_family": "opd_stabilization",
        "method_role": "freshness_aware_long_horizon_opd",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["discussion_outlook"],
        "source_locator": "arXiv:2605.17862v1, Sections 3-4",
        "source_heading": "f-OPD: Stabilizing Long-Horizon On-Policy Distillation with Freshness-Aware Control",
        "claim_boundary": "freshness-aware asynchronous OPD context only; no f-OPD benchmark is reproduced",
    },
    {
        "citation_key": "ke2019f_divergence_imitation",
        "source_kind": "primary_preprint",
        "source_family": "kl_geometry_caveats",
        "method_role": "imitation_learning_divergence_design",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/divergence_demo.json",
        "manuscript_sections": ["methods_analytical", "discussion_outlook"],
        "claim_boundary": "divergence-design bridge for imitation only; local divergence values are generated",
    },
    {
        "citation_key": "hernandezlobato2016blackbox_alpha",
        "source_kind": "primary_conference",
        "source_family": "kl_geometry_caveats",
        "method_role": "alpha_divergence_interpolation",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/divergence_demo.json",
        "manuscript_sections": ["methods_analytical", "discussion_outlook"],
        "claim_boundary": "alpha-divergence interpolation context only",
    },
    {
        "citation_key": "shrivastava2021mi_kd",
        "source_kind": "primary_preprint",
        "source_family": "mutual_information_distillation",
        "method_role": "mutual_information_kd_context",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/parameter_sweep.csv",
        "manuscript_sections": ["methods_analytical", "results_mi_sweep"],
        "claim_boundary": "MI-for-KD context only; Bernoulli-Ising MI values are generated locally",
    },
    {
        "citation_key": "fellows2018virel",
        "source_kind": "primary_conference",
        "source_family": "control_as_inference",
        "method_role": "variational_em_actor_critic_bridge",
        "tracks": ["formalism", "scholarship"],
        "artifact": "output/data/firstprinciples/variational_em_demo.json",
        "manuscript_sections": ["methods_analytical", "discussion_outlook"],
        "claim_boundary": "VIREL/variational-EM bridge only; local EM loop is a toy artifact",
    },
    {
        "citation_key": "zhong2026sod",
        "source_kind": "primary_preprint",
        "source_family": "agentic_long_horizon_opd",
        "method_role": "stepwise_agentic_opd_reliability",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["discussion_outlook"],
        "claim_boundary": "agentic OPD context only; no tool-use benchmark is reproduced",
    },
    {
        "citation_key": "zhang2026opsdl",
        "source_kind": "primary_preprint",
        "source_family": "agentic_long_horizon_opd",
        "method_role": "long_context_on_policy_self_distillation",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["discussion_outlook"],
        "claim_boundary": "long-context OPD context only; no long-context benchmark is reproduced",
    },
    {
        "citation_key": "tian2026vicur",
        "source_kind": "primary_preprint",
        "source_family": "multimodal_privileged_opd",
        "method_role": "recoverable_visual_privilege",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["discussion_outlook"],
        "claim_boundary": "multimodal privilege future-work context only",
    },
    {
        "citation_key": "liu2026visual_advantage_opd",
        "source_kind": "primary_preprint",
        "source_family": "multimodal_privileged_opd",
        "method_role": "visual_advantage_token_weighting",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["discussion_outlook"],
        "claim_boundary": "vision-language OPD future-work context only",
    },
)


# Sources added in response to the 2026-06-10 external manuscript review:
# countervailing exposure-bias / scheduled-sampling / FEP-critique / diversity
# literature plus a primary offline-OPD efficiency reference. Every entry was
# live-verified (arXiv abs page or DOI redirect) before inclusion.
_RUN5_REVIEW_SOURCES: tuple[dict[str, Any], ...] = (
    {
        "citation_key": "huszar2015hownot",
        "source_kind": "primary_preprint",
        "source_family": "sequence_training_critique",
        "method_role": "scheduled_sampling_objection",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/exposure_bias_demo.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "counter-citation: scheduled sampling cited as lineage, not settled solution",
    },
    {
        "citation_key": "ranzato2016sequence",
        "source_kind": "primary_conference",
        "source_family": "sequence_training_critique",
        "method_role": "sequence_level_objective",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/exposure_bias_demo.json",
        "manuscript_sections": ["intro_motivation"],
        "claim_boundary": "historical sequence-level train/test mismatch lineage only",
    },
    {
        "citation_key": "he2021selfrecovery",
        "source_kind": "primary_conference",
        "source_family": "sequence_training_critique",
        "method_role": "exposure_bias_counterweight",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/exposure_bias_demo.json",
        "manuscript_sections": ["intro_motivation", "discussion_outlook"],
        "claim_boundary": "counter-citation: exposure-bias severity is task-dependent; motivational use only",
    },
    {
        "citation_key": "biehl2020critique",
        "source_kind": "primary_article",
        "source_family": "free_energy_principle_critique",
        "method_role": "blanket_interpretation_boundary",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/scholarship_source_matrix.json",
        "manuscript_sections": ["intro_motivation", "intro_contributions", "discussion_outlook"],
        "claim_boundary": "limitation citation: blanket readings constrained to toy probabilistic interpretation",
    },
    {
        "citation_key": "holtzman2019degeneration",
        "source_kind": "primary_conference",
        "source_family": "neural_generation_diversity",
        "method_role": "diversity_collapse_context",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/diversity_demo.json",
        "manuscript_sections": ["discussion_outlook"],
        "claim_boundary": "adjacent generation-diversity literature; no decoding experiment is run here",
    },
    {
        "citation_key": "wu2026lightningopd",
        "source_kind": "primary_preprint",
        "source_family": "opd_efficiency",
        "method_role": "offline_opd_teacher_consistency",
        "tracks": ["prose", "scholarship"],
        "artifact": "output/data/firstprinciples/opd_taxonomy.json",
        "manuscript_sections": ["discussion_outlook"],
        "claim_boundary": "external efficiency context only; no production-scale claim is reproduced",
    },
)
