"""Neutral artifact and pipeline contracts for generated project outputs.

This module is intentionally dependency-light. Manuscript composition,
roadmap-track builders, gates, and tests all import these constants instead of
importing each other for shared metadata.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ScriptStep:
    """One configured analysis script in deterministic pipeline order."""

    name: str
    script: str


DEFAULT_ANALYSIS_SCRIPTS: tuple[ScriptStep, ...] = (
    ScriptStep("compose_manuscript", "compose_manuscript.py"),
    ScriptStep("run_analytical_sweep", "run_analytical_sweep.py"),
    ScriptStep("simulate_si_tmaze", "simulate_si_tmaze.py"),
    ScriptStep("simulate_si_graph_world", "simulate_si_graph_world.py"),
    ScriptStep("compute_statistics", "compute_statistics.py"),
    ScriptStep("generate_firstprinciples", "generate_firstprinciples.py"),
    ScriptStep("generate_figures", "generate_figures.py"),
    ScriptStep("render_animation", "render_animation.py"),
    ScriptStep("generate_validation_spine", "generate_validation_spine.py"),
    ScriptStep("generate_toy_sweep_tracks", "generate_toy_sweep_tracks.py"),
    ScriptStep("generate_formal_interop_tracks", "generate_formal_interop_tracks.py"),
    ScriptStep("generate_integration_audit", "generate_integration_audit.py"),
    ScriptStep("generate_sheaf_tracks", "generate_sheaf_tracks.py"),
    ScriptStep("generate_manuscript_variables", "z_generate_manuscript_variables.py"),
)



def _unique(values: tuple[str, ...]) -> tuple[str, ...]:
    """Return values in declaration order with duplicates removed."""
    return tuple(dict.fromkeys(values))


REQUIRED_OUTPUTS: tuple[str, ...] = _unique((
    "output/data/parameter_sweep.csv",
    "output/data/si_tmaze_summary.json",
    "output/data/si_tmaze_trace.json",
    "output/data/si_tmaze_model_matrices.json",
    "output/data/analysis_statistics.json",
    "output/figures/ising_mi_curve.png",
    "output/figures/free_energy_curve.png",
    "output/figures/si_tmaze_actions.png",
    "output/figures/si_belief_entropy_curve.png",
    "output/figures/si_obs_action_trace.png",
    "output/figures/si_tmaze_model_matrices.png",
    "output/figures/distillation_divergence_geometry.png",
    "output/figures/exposure_bias_recovery.png",
    "output/figures/classroom_distillation_signal.png",
    "output/figures/energy_decomposition.png",
    "output/figures/parallel_convergence.png",
    "output/figures/diversity_tradeoff.png",
    "output/figures/sheaf_layers_overview.png",
    "output/figures/sheaf_coverage_heatmap.png",
    "output/figures/invariant_dashboard.png",
    "output/figures/tmaze_schematic.png",
    "output/figures/multi_track_architecture.png",
    "output/figures/lean_boundary_status.png",
    "output/figures/gnn_ontology_concordance.png",
    "output/figures/semantic_gluing_graph.png",
    "output/figures/theorem_traceability_graph.png",
    "output/figures/causal_ablation_heatmap.png",
    "output/figures/figure_registry.json",
    "output/figures/graphical_abstract.png",
    "output/figures/si_tmaze_model_matrices.png",
    "output/data/sheaf_coverage_matrix.json",
    "output/data/sheaf_gluing_certificate.json",
    "output/data/sheaf_evidence_crosswalk.json",
    "output/data/validation_dependency_graph.json",
    "output/data/sheaf_section_status_matrix.json",
    "output/reports/sheaf_render_log.json",
    "output/data/artifact_provenance.json",
    "output/data/analytical_assumption_index.json",
    "output/data/si_policy_comparison.json",
    "output/data/pymdp_policy_posterior_grid.json",
    "output/data/si_tmaze_model_matrices.json",
    "output/reports/pymdp_runtime_diagnostics.json",
    "output/data/si_graph_world_summary.json",
    "output/data/si_graph_world_trace.json",
    "output/reports/invariants.json",
    "output/reports/si_invariants.json",
    "output/reports/si_tmaze_run_report.json",
    "output/reports/reproducibility_replay.json",
    "output/reports/counterexample_matrix.json",
    "output/data/analytical_observable_sweep.json",
    "output/data/sensitivity_sweep.json",
    "output/data/uncertainty_summary.json",
    "output/data/toy_benchmark_matrix.json",
    "output/data/si_policy_grid.json",
    "output/data/si_efe_terms.json",
    "output/data/si_graph_world_topology_sweep.json",
    "output/data/si_graph_world_topology_traces.json",
    "output/reports/graph_world_invariants.json",
    "output/reports/model_checking_witnesses.json",
    "output/data/interop_roundtrip_report.json",
    "output/data/gnn_roundtrip_report.json",
    "output/reports/gnn_lint_report.json",
    "output/data/ontology_alias_index.json",
    "output/data/ontology_profile_matrix.json",
    "output/reports/lean_theorem_inventory.json",
    "output/reports/lean_graph_world_inventory.json",
    "output/reports/producer_completeness.json",
    "output/reports/stale_artifact_report.json",
    "output/data/cross_track_symbol_table.json",
    "output/data/manuscript_evidence_tables.json",
    "output/data/manuscript_token_provenance.json",
    "output/reports/manuscript_hardcoded_variable_audit.json",
    "output/reports/claim_evidence_audit.json",
    "output/data/validation_gate_index.json",
    "output/data/figure_source_map.json",
    "output/reports/figure_hash_manifest.json",
    "output/reports/scope_boundary_audit.json",
    "output/reports/adversarial_audit.json",
    "output/reports/replay_matrix.json",
    "output/data/track_improvement_scope.json",
    "output/reports/blocked_scope_manifest.json",
    "output/data/evidence_field_index.json",
    "output/reports/release_bundle_manifest.json",
    "output/data/theorem_traceability_matrix.json",
    "output/reports/artifact_diffoscope.json",
    "output/data/proof_extraction_index.json",
    "output/data/state_space_catalog.json",
    "output/data/causal_ablation_matrix.json",
    "output/reports/artifact_license_audit.json",
    "output/reports/release_notes_evidence.json",
    "output/data/scholarship_source_matrix.json",
    "output/figures/scholarship_source_map.png",
    "output/data/firstprinciples/correspondence_map.json",
    "output/data/firstprinciples/opd_taxonomy.json",
    "output/data/firstprinciples/divergence_demo.json",
    "output/data/firstprinciples/reward_tilting_demo.json",
    "output/data/firstprinciples/exposure_bias_demo.json",
    "output/data/firstprinciples/sdpg_demo.json",
    "output/data/firstprinciples/statistics_demo.json",
    "output/data/firstprinciples/empirical_benchmark.json",
    "output/data/firstprinciples/benchmark_table.md",
    "output/data/firstprinciples/classroom.json",
    "output/data/proof_dependency_graph.json",
    "output/data/state_transition_table.json",
    "output/reports/ablation_sensitivity_report.json",
    "output/reports/release_attestation.json",
    "output/figures/si_belief_trajectory.gif",
    "output/data/animation_frame_deltas.json",
    "output/reports/manuscript_staleness_report.json",
))

REQUIRED_OUTPUT_CHECK_KEYS: tuple[str, ...] = _unique((
    "output/data/parameter_sweep.csv",
    "output/data/analysis_statistics.json",
    "output/data/sheaf_coverage_matrix.json",
    "output/data/sheaf_gluing_certificate.json",
    "output/data/sheaf_evidence_crosswalk.json",
    "output/data/validation_dependency_graph.json",
    "output/data/sheaf_section_status_matrix.json",
    "output/reports/sheaf_render_log.json",
    "output/data/artifact_provenance.json",
    "output/data/analytical_assumption_index.json",
    "output/data/si_policy_comparison.json",
    "output/data/pymdp_policy_posterior_grid.json",
    "output/reports/pymdp_runtime_diagnostics.json",
    "output/data/si_graph_world_summary.json",
    "output/data/si_tmaze_summary.json",
    "output/figures/ising_mi_curve.png",
    "output/figures/sheaf_coverage_heatmap.png",
    "output/figures/sheaf_layers_overview.png",
    "output/figures/semantic_gluing_graph.png",
    "output/figures/theorem_traceability_graph.png",
    "output/figures/causal_ablation_heatmap.png",
    "output/figures/distillation_divergence_geometry.png",
    "output/figures/exposure_bias_recovery.png",
    "output/figures/classroom_distillation_signal.png",
    "output/figures/energy_decomposition.png",
    "output/figures/parallel_convergence.png",
    "output/figures/diversity_tradeoff.png",
    "output/figures/invariant_dashboard.png",
    "output/figures/figure_registry.json",
    "output/figures/graphical_abstract.png",
    "output/reports/si_invariants.json",
    "output/reports/si_tmaze_run_report.json",
    "output/reports/reproducibility_replay.json",
    "output/reports/counterexample_matrix.json",
    "output/data/sensitivity_sweep.json",
    "output/data/si_graph_world_topology_traces.json",
    "output/data/uncertainty_summary.json",
    "output/data/toy_benchmark_matrix.json",
    "output/data/interop_roundtrip_report.json",
    "output/reports/model_checking_witnesses.json",
    "output/reports/adversarial_audit.json",
    "output/reports/replay_matrix.json",
    "output/data/track_improvement_scope.json",
    "output/reports/blocked_scope_manifest.json",
    "output/data/evidence_field_index.json",
    "output/reports/release_bundle_manifest.json",
    "output/data/theorem_traceability_matrix.json",
    "output/reports/artifact_diffoscope.json",
    "output/data/proof_extraction_index.json",
    "output/data/state_space_catalog.json",
    "output/data/causal_ablation_matrix.json",
    "output/reports/artifact_license_audit.json",
    "output/reports/release_notes_evidence.json",
    "output/data/scholarship_source_matrix.json",
    "output/figures/scholarship_source_map.png",
    "output/reports/manuscript_hardcoded_variable_audit.json",
    "output/data/firstprinciples/divergence_demo.json",
    "output/data/firstprinciples/exposure_bias_demo.json",
    "output/data/firstprinciples/statistics_demo.json",
    "output/data/firstprinciples/empirical_benchmark.json",
    "output/data/firstprinciples/benchmark_table.md",
    "output/data/firstprinciples/classroom.json",
    "output/data/proof_dependency_graph.json",
    "output/data/state_transition_table.json",
    "output/reports/ablation_sensitivity_report.json",
    "output/reports/release_attestation.json",
    "output/reports/scope_boundary_audit.json",
    "output/data/animation_frame_deltas.json",
    "output/reports/manuscript_staleness_report.json",
))

SEMANTIC_SCHEMA = "template_active_inference.semantic_gluing.v2"

ARTIFACT_PRODUCERS: dict[str, str] = {
    "output/data/parameter_sweep.csv": "run_analytical_sweep.py",
    "output/data/si_tmaze_summary.json": "simulate_si_tmaze.py",
    "output/data/si_tmaze_trace.json": "simulate_si_tmaze.py",
    "output/data/si_tmaze_model_matrices.json": "simulate_si_tmaze.py",
    "output/data/si_policy_comparison.json": "simulate_si_tmaze.py",
    "output/data/pymdp_policy_posterior_grid.json": "simulate_si_tmaze.py",
    "output/reports/pymdp_runtime_diagnostics.json": "simulate_si_tmaze.py",
    "output/data/si_graph_world_summary.json": "simulate_si_graph_world.py",
    "output/data/si_graph_world_trace.json": "simulate_si_graph_world.py",
    "output/data/analysis_statistics.json": "compute_statistics.py",
    "output/data/sheaf_coverage_matrix.json": "generate_figures.py",
    "output/data/manuscript_variables.json": "z_generate_manuscript_variables.py",
    "output/data/sheaf_evidence_crosswalk.json": "generate_sheaf_tracks.py",
    "output/data/validation_dependency_graph.json": "generate_sheaf_tracks.py",
    "output/data/sheaf_gluing_certificate.json": "generate_sheaf_tracks.py",
    "output/data/sheaf_section_status_matrix.json": "generate_sheaf_tracks.py",
    "output/reports/sheaf_render_log.json": "generate_sheaf_tracks.py",
    "output/data/artifact_provenance.json": "generate_sheaf_tracks.py",
    "output/figures/semantic_gluing_graph.png": "generate_figures.py",
    "output/figures/theorem_traceability_graph.png": "generate_figures.py",
    "output/figures/causal_ablation_heatmap.png": "generate_figures.py",
    "output/figures/graphical_abstract.png": "generate_figures.py",
    "output/figures/si_tmaze_model_matrices.png": "generate_figures.py",
    "output/figures/distillation_divergence_geometry.png": "generate_figures.py",
    "output/figures/exposure_bias_recovery.png": "generate_figures.py",
    "output/figures/classroom_distillation_signal.png": "generate_figures.py",
    "output/figures/ising_mi_curve.png": "generate_figures.py",
    "output/figures/free_energy_curve.png": "generate_figures.py",
    "output/figures/si_tmaze_actions.png": "generate_figures.py",
    "output/figures/si_belief_entropy_curve.png": "generate_figures.py",
    "output/figures/si_obs_action_trace.png": "generate_figures.py",
    "output/figures/energy_decomposition.png": "generate_figures.py",
    "output/figures/parallel_convergence.png": "generate_figures.py",
    "output/figures/diversity_tradeoff.png": "generate_figures.py",
    "output/figures/invariant_dashboard.png": "generate_figures.py",
    "output/figures/tmaze_schematic.png": "generate_figures.py",
    "output/figures/multi_track_architecture.png": "generate_figures.py",
    "output/figures/lean_boundary_status.png": "generate_figures.py",
    "output/figures/gnn_ontology_concordance.png": "generate_figures.py",
    "output/figures/si_belief_trajectory.gif": "render_animation.py",
    "output/data/animation_frame_deltas.json": "render_animation.py",
    "output/figures/sheaf_layers_overview.png": "generate_figures.py",
    "output/figures/sheaf_coverage_heatmap.png": "generate_figures.py",
    "output/figures/figure_registry.json": "generate_figures.py",
    "output/reports/invariants.json": "run_analytical_sweep.py",
    "output/reports/si_invariants.json": "simulate_si_tmaze.py",
    "output/reports/si_tmaze_run_report.json": "simulate_si_tmaze.py",
    "output/reports/reproducibility_replay.json": "generate_validation_spine.py",
    "output/reports/counterexample_matrix.json": "generate_sheaf_tracks.py",
    "output/data/analytical_assumption_index.json": "generate_toy_sweep_tracks.py",
    "output/data/analytical_observable_sweep.json": "generate_toy_sweep_tracks.py",
    "output/data/sensitivity_sweep.json": "generate_sheaf_tracks.py",
    "output/data/uncertainty_summary.json": "generate_sheaf_tracks.py",
    "output/data/toy_benchmark_matrix.json": "generate_toy_sweep_tracks.py",
    "output/data/si_policy_grid.json": "generate_toy_sweep_tracks.py",
    "output/data/si_efe_terms.json": "generate_toy_sweep_tracks.py",
    "output/data/si_graph_world_topology_sweep.json": "generate_toy_sweep_tracks.py",
    "output/data/si_graph_world_topology_traces.json": "generate_toy_sweep_tracks.py",
    "output/reports/graph_world_invariants.json": "generate_toy_sweep_tracks.py",
    "output/reports/model_checking_witnesses.json": "generate_sheaf_tracks.py",
    "output/data/interop_roundtrip_report.json": "generate_sheaf_tracks.py",
    "output/data/gnn_roundtrip_report.json": "generate_formal_interop_tracks.py",
    "output/reports/gnn_lint_report.json": "generate_formal_interop_tracks.py",
    "output/data/ontology_alias_index.json": "generate_formal_interop_tracks.py",
    "output/data/ontology_profile_matrix.json": "generate_formal_interop_tracks.py",
    "output/reports/lean_theorem_inventory.json": "generate_formal_interop_tracks.py",
    "output/reports/lean_graph_world_inventory.json": "generate_formal_interop_tracks.py",
    "output/reports/producer_completeness.json": "generate_integration_audit.py",
    "output/reports/stale_artifact_report.json": "generate_integration_audit.py",
    "output/data/cross_track_symbol_table.json": "generate_integration_audit.py",
    "output/data/manuscript_evidence_tables.json": "generate_integration_audit.py",
    "output/data/manuscript_token_provenance.json": "generate_integration_audit.py",
    "output/reports/manuscript_hardcoded_variable_audit.json": "generate_integration_audit.py",
    "output/reports/claim_evidence_audit.json": "generate_integration_audit.py",
    "output/data/validation_gate_index.json": "generate_integration_audit.py",
    "output/data/figure_source_map.json": "generate_integration_audit.py",
    "output/reports/figure_hash_manifest.json": "generate_integration_audit.py",
    "output/reports/scope_boundary_audit.json": "generate_integration_audit.py",
    "output/reports/adversarial_audit.json": "generate_sheaf_tracks.py",
    "output/reports/manuscript_staleness_report.json": "z_generate_manuscript_variables.py",
    "output/reports/replay_matrix.json": "generate_sheaf_tracks.py",
    "output/data/track_improvement_scope.json": "generate_sheaf_tracks.py",
    "output/reports/blocked_scope_manifest.json": "generate_sheaf_tracks.py",
    "output/data/evidence_field_index.json": "generate_sheaf_tracks.py",
    "output/reports/release_bundle_manifest.json": "generate_sheaf_tracks.py",
    "output/data/theorem_traceability_matrix.json": "generate_sheaf_tracks.py",
    "output/reports/artifact_diffoscope.json": "generate_integration_audit.py",
    "output/data/proof_extraction_index.json": "generate_formal_interop_tracks.py",
    "output/data/state_space_catalog.json": "generate_toy_sweep_tracks.py",
    "output/data/causal_ablation_matrix.json": "generate_toy_sweep_tracks.py",
    "output/reports/artifact_license_audit.json": "generate_integration_audit.py",
    "output/reports/release_notes_evidence.json": "generate_integration_audit.py",
    "output/data/scholarship_source_matrix.json": "generate_sheaf_tracks.py",
    "output/figures/scholarship_source_map.png": "generate_figures.py",
    "output/data/firstprinciples/correspondence_map.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/opd_taxonomy.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/divergence_demo.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/reward_tilting_demo.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/exposure_bias_demo.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/sdpg_demo.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/correspondence_table.md": "generate_firstprinciples.py",
    "output/data/firstprinciples/taxonomy_table.md": "generate_firstprinciples.py",
    "output/data/firstprinciples/statistics_demo.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/empirical_benchmark.json": "generate_firstprinciples.py",
    "output/data/firstprinciples/benchmark_table.md": "generate_firstprinciples.py",
    "output/data/firstprinciples/classroom.json": "generate_firstprinciples.py",
    "output/data/proof_dependency_graph.json": "generate_sheaf_tracks.py",
    "output/data/state_transition_table.json": "generate_sheaf_tracks.py",
    "output/reports/ablation_sensitivity_report.json": "generate_sheaf_tracks.py",
    "output/reports/release_attestation.json": "generate_sheaf_tracks.py",
}

ARTIFACT_CONSUMERS: dict[str, tuple[str, ...]] = {
    "output/data/parameter_sweep.csv": ("methods_analytical", "results_mi_sweep"),
    "output/data/si_tmaze_summary.json": ("methods_pymdp", "results_si_tmaze"),
    "output/data/si_tmaze_trace.json": ("methods_pymdp", "results_si_tmaze"),
    "output/data/si_tmaze_model_matrices.json": ("methods_pymdp", "results_si_tmaze", "appendix_full_sheaf"),
    "output/data/si_policy_comparison.json": ("methods_pymdp", "results_si_tmaze"),
    "output/data/pymdp_policy_posterior_grid.json": ("methods_pymdp", "appendix_full_sheaf"),
    "output/reports/pymdp_runtime_diagnostics.json": ("methods_pymdp", "appendix_full_sheaf"),
    "output/data/si_graph_world_summary.json": ("methods_pymdp", "results_si_tmaze"),
    "output/data/si_graph_world_trace.json": ("methods_pymdp", "results_si_tmaze", "appendix_full_sheaf"),
    "output/data/analysis_statistics.json": ("results_si_tmaze", "results_invariants"),
    "output/data/sheaf_coverage_matrix.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/manuscript_variables.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/sheaf_gluing_certificate.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/sheaf_evidence_crosswalk.json": ("methods_sheaf",),
    "output/data/validation_dependency_graph.json": ("methods_sheaf",),
    "output/data/sheaf_section_status_matrix.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/sheaf_render_log.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/artifact_provenance.json": ("methods_sheaf",),
    "output/reports/counterexample_matrix.json": ("methods_sheaf",),
    "output/reports/replay_matrix.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/analytical_assumption_index.json": ("methods_analytical", "appendix_full_sheaf"),
    "output/data/sensitivity_sweep.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/uncertainty_summary.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/toy_benchmark_matrix.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/si_policy_grid.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/si_efe_terms.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/analytical_observable_sweep.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/si_graph_world_topology_sweep.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/si_graph_world_topology_traces.json": ("results_invariants", "appendix_full_sheaf"),
    "output/reports/graph_world_invariants.json": ("results_invariants", "appendix_full_sheaf"),
    "output/reports/model_checking_witnesses.json": ("methods_lean", "appendix_full_sheaf"),
    "output/data/interop_roundtrip_report.json": ("methods_pymdp", "appendix_full_sheaf"),
    "output/data/gnn_roundtrip_report.json": ("methods_pymdp", "appendix_full_sheaf"),
    "output/reports/gnn_lint_report.json": ("methods_pymdp", "appendix_full_sheaf"),
    "output/data/ontology_alias_index.json": ("methods_pymdp", "appendix_full_sheaf"),
    "output/data/ontology_profile_matrix.json": ("methods_pymdp", "appendix_full_sheaf"),
    "output/reports/lean_theorem_inventory.json": ("methods_lean", "appendix_full_sheaf"),
    "output/reports/lean_graph_world_inventory.json": ("methods_lean", "appendix_full_sheaf"),
    "output/reports/producer_completeness.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/stale_artifact_report.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/cross_track_symbol_table.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/manuscript_evidence_tables.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/manuscript_token_provenance.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/manuscript_hardcoded_variable_audit.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/claim_evidence_audit.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/validation_gate_index.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/figure_source_map.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/figure_hash_manifest.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/scope_boundary_audit.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/adversarial_audit.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/manuscript_staleness_report.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/track_improvement_scope.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/blocked_scope_manifest.json": ("methods_sheaf", "discussion_outlook", "appendix_full_sheaf"),
    "output/data/evidence_field_index.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/release_bundle_manifest.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/theorem_traceability_matrix.json": ("methods_lean", "appendix_full_sheaf"),
    "output/reports/artifact_diffoscope.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/proof_extraction_index.json": ("methods_lean", "appendix_full_sheaf"),
    "output/data/state_space_catalog.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/causal_ablation_matrix.json": ("results_invariants", "appendix_full_sheaf"),
    "output/reports/artifact_license_audit.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/release_notes_evidence.json": ("discussion_outlook", "appendix_full_sheaf"),
    "output/data/scholarship_source_matrix.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/figures/scholarship_source_map.png": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/firstprinciples/correspondence_map.json": (
        "intro_contributions",
        "methods_analytical",
        "methods_sheaf",
        "discussion_outlook",
    ),
    "output/data/firstprinciples/opd_taxonomy.json": (
        "intro_motivation",
        "methods_sheaf",
        "discussion_outlook",
    ),
    "output/data/firstprinciples/divergence_demo.json": ("methods_analytical", "discussion_outlook"),
    "output/data/firstprinciples/reward_tilting_demo.json": ("methods_analytical", "discussion_outlook"),
    "output/data/firstprinciples/exposure_bias_demo.json": (
        "intro_motivation",
        "methods_pymdp",
        "discussion_outlook",
    ),
    "output/data/firstprinciples/sdpg_demo.json": ("methods_analytical", "discussion_outlook"),
    "output/data/firstprinciples/correspondence_table.md": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/firstprinciples/taxonomy_table.md": ("methods_sheaf", "appendix_full_sheaf"),
    "output/data/firstprinciples/statistics_demo.json": ("results_invariants", "appendix_full_sheaf"),
    "output/data/firstprinciples/empirical_benchmark.json": ("discussion_outlook", "appendix_full_sheaf"),
    "output/data/firstprinciples/benchmark_table.md": ("appendix_full_sheaf",),
    "output/data/firstprinciples/classroom.json": (
        "intro_motivation",
        "results_si_tmaze",
        "discussion_outlook",
    ),
    "output/data/proof_dependency_graph.json": ("methods_lean", "appendix_full_sheaf"),
    "output/data/state_transition_table.json": ("results_invariants", "appendix_full_sheaf"),
    "output/reports/ablation_sensitivity_report.json": ("results_invariants", "appendix_full_sheaf"),
    "output/reports/release_attestation.json": ("discussion_outlook", "appendix_full_sheaf"),
    "output/reports/reproducibility_replay.json": ("results_invariants",),
    "output/figures/semantic_gluing_graph.png": ("methods_sheaf",),
    "output/figures/theorem_traceability_graph.png": ("appendix_full_sheaf",),
    "output/figures/causal_ablation_heatmap.png": ("appendix_full_sheaf",),
    "output/figures/graphical_abstract.png": ("front_matter",),
    "output/figures/si_tmaze_model_matrices.png": ("methods_pymdp", "results_si_tmaze", "appendix_full_sheaf"),
    "output/figures/distillation_divergence_geometry.png": ("methods_analytical",),
    "output/figures/exposure_bias_recovery.png": ("intro_contributions",),
    "output/figures/classroom_distillation_signal.png": ("results_si_tmaze",),
    "output/figures/ising_mi_curve.png": ("methods_analytical", "results_mi_sweep", "appendix_full_sheaf"),
    "output/figures/free_energy_curve.png": ("results_free_energy",),
    "output/figures/si_tmaze_actions.png": ("results_si_tmaze", "appendix_full_sheaf"),
    "output/figures/si_belief_entropy_curve.png": ("results_si_tmaze",),
    "output/figures/si_obs_action_trace.png": ("results_si_tmaze",),
    "output/figures/energy_decomposition.png": ("results_free_energy",),
    "output/figures/parallel_convergence.png": ("methods_pymdp",),
    "output/figures/diversity_tradeoff.png": ("results_invariants",),
    "output/figures/invariant_dashboard.png": ("results_invariants",),
    "output/figures/tmaze_schematic.png": ("methods_pymdp",),
    "output/figures/multi_track_architecture.png": ("intro_motivation", "intro_contributions"),
    "output/figures/lean_boundary_status.png": ("methods_lean", "appendix_full_sheaf"),
    "output/figures/gnn_ontology_concordance.png": (
        "intro_contributions",
        "methods_analytical",
        "methods_pymdp",
        "appendix_full_sheaf",
    ),
    "output/figures/si_belief_trajectory.gif": ("appendix_full_sheaf",),
    "output/data/animation_frame_deltas.json": ("appendix_full_sheaf",),
    "output/figures/sheaf_layers_overview.png": ("methods_sheaf",),
    "output/figures/sheaf_coverage_heatmap.png": ("appendix_full_sheaf",),
    "output/figures/figure_registry.json": ("methods_sheaf", "appendix_full_sheaf"),
    "output/reports/invariants.json": ("results_invariants",),
    "output/reports/si_invariants.json": ("results_si_tmaze",),
    "output/reports/si_tmaze_run_report.json": ("results_si_tmaze",),
}

ARTIFACT_GATES: dict[str, tuple[str, ...]] = {
    "output/data/parameter_sweep.csv": ("validate_outputs",),
    "output/data/si_tmaze_summary.json": ("validate_outputs",),
    "output/data/si_tmaze_trace.json": ("validate_outputs",),
    "output/data/si_tmaze_model_matrices.json": ("validate_outputs", "validate_manuscript"),
    "output/data/analysis_statistics.json": ("validate_outputs",),
    "output/data/sheaf_coverage_matrix.json": ("validate_outputs", "validate_manuscript"),
    "output/data/manuscript_variables.json": ("validate_manuscript",),
    "output/data/sheaf_gluing_certificate.json": ("validate_manuscript", "validate_outputs"),
    "output/data/sheaf_evidence_crosswalk.json": ("validate_manuscript", "validate_outputs"),
    "output/data/validation_dependency_graph.json": ("validate_manuscript", "validate_outputs"),
    "output/data/sheaf_section_status_matrix.json": ("validate_manuscript", "validate_outputs"),
    "output/reports/sheaf_render_log.json": ("validate_manuscript", "validate_outputs"),
    "output/data/artifact_provenance.json": ("validate_manuscript", "validate_outputs"),
    "output/reports/replay_matrix.json": ("validate_outputs", "validate_manuscript"),
    "output/data/si_policy_comparison.json": ("validate_outputs",),
    "output/data/pymdp_policy_posterior_grid.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/pymdp_runtime_diagnostics.json": ("validate_outputs", "validate_manuscript"),
    "output/data/si_graph_world_summary.json": ("validate_outputs",),
    "output/data/si_graph_world_trace.json": ("validate_outputs",),
    "output/figures/si_belief_trajectory.gif": ("validate_outputs",),
    "output/figures/semantic_gluing_graph.png": ("validate_outputs", "figure_registry"),
    "output/figures/theorem_traceability_graph.png": ("validate_outputs", "figure_registry"),
    "output/figures/causal_ablation_heatmap.png": ("validate_outputs", "figure_registry"),
    "output/figures/graphical_abstract.png": ("validate_outputs", "figure_registry"),
    "output/figures/si_tmaze_model_matrices.png": ("validate_outputs", "figure_registry"),
    "output/figures/distillation_divergence_geometry.png": ("validate_outputs", "figure_registry"),
    "output/figures/exposure_bias_recovery.png": ("validate_outputs", "figure_registry"),
    "output/figures/classroom_distillation_signal.png": ("validate_outputs", "figure_registry"),
    "output/figures/ising_mi_curve.png": ("validate_outputs", "figure_registry"),
    "output/figures/free_energy_curve.png": ("validate_outputs", "figure_registry"),
    "output/figures/si_tmaze_actions.png": ("validate_outputs", "figure_registry"),
    "output/figures/si_belief_entropy_curve.png": ("validate_outputs", "figure_registry"),
    "output/figures/si_obs_action_trace.png": ("validate_outputs", "figure_registry"),
    "output/figures/energy_decomposition.png": ("validate_outputs", "figure_registry"),
    "output/figures/parallel_convergence.png": ("validate_outputs", "figure_registry"),
    "output/figures/diversity_tradeoff.png": ("validate_outputs", "figure_registry"),
    "output/figures/invariant_dashboard.png": ("validate_outputs", "figure_registry"),
    "output/figures/tmaze_schematic.png": ("validate_outputs", "figure_registry"),
    "output/figures/multi_track_architecture.png": ("validate_outputs", "figure_registry"),
    "output/figures/lean_boundary_status.png": ("validate_outputs", "figure_registry"),
    "output/figures/gnn_ontology_concordance.png": ("validate_outputs", "figure_registry"),
    "output/reports/reproducibility_replay.json": ("validate_outputs",),
    "output/reports/counterexample_matrix.json": ("validate_outputs", "validate_manuscript"),
    "output/data/analytical_assumption_index.json": ("validate_outputs", "validate_manuscript"),
    "output/data/analytical_observable_sweep.json": ("validate_outputs",),
    "output/data/sensitivity_sweep.json": ("validate_outputs",),
    "output/data/uncertainty_summary.json": ("validate_outputs",),
    "output/data/toy_benchmark_matrix.json": ("validate_outputs",),
    "output/data/si_policy_grid.json": ("validate_outputs",),
    "output/data/si_efe_terms.json": ("validate_outputs",),
    "output/data/si_graph_world_topology_sweep.json": ("validate_outputs",),
    "output/data/si_graph_world_topology_traces.json": ("validate_outputs",),
    "output/reports/graph_world_invariants.json": ("validate_outputs",),
    "output/reports/model_checking_witnesses.json": ("validate_outputs",),
    "output/data/interop_roundtrip_report.json": ("validate_outputs",),
    "output/data/gnn_roundtrip_report.json": ("validate_outputs",),
    "output/reports/gnn_lint_report.json": ("validate_outputs",),
    "output/data/ontology_alias_index.json": ("validate_outputs",),
    "output/data/ontology_profile_matrix.json": ("validate_outputs",),
    "output/reports/lean_theorem_inventory.json": ("validate_outputs",),
    "output/reports/lean_graph_world_inventory.json": ("validate_outputs",),
    "output/reports/producer_completeness.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/stale_artifact_report.json": ("validate_outputs", "validate_manuscript"),
    "output/data/cross_track_symbol_table.json": ("validate_outputs", "validate_manuscript"),
    "output/data/manuscript_evidence_tables.json": ("validate_outputs", "validate_manuscript"),
    "output/data/manuscript_token_provenance.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/manuscript_hardcoded_variable_audit.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/claim_evidence_audit.json": ("validate_outputs", "validate_manuscript"),
    "output/data/validation_gate_index.json": ("validate_outputs", "validate_manuscript"),
    "output/data/figure_source_map.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/figure_hash_manifest.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/scope_boundary_audit.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/adversarial_audit.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/manuscript_staleness_report.json": ("validate_outputs", "validate_manuscript"),
    "output/data/animation_frame_deltas.json": ("validate_outputs", "validate_manuscript"),
    "output/figures/sheaf_layers_overview.png": ("validate_outputs", "figure_registry"),
    "output/figures/sheaf_coverage_heatmap.png": ("validate_outputs", "figure_registry"),
    "output/figures/figure_registry.json": ("validate_outputs",),
    "output/reports/invariants.json": ("validate_outputs",),
    "output/reports/si_invariants.json": ("validate_outputs",),
    "output/reports/si_tmaze_run_report.json": ("validate_outputs",),
    "output/data/track_improvement_scope.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/blocked_scope_manifest.json": ("validate_outputs", "validate_manuscript"),
    "output/data/evidence_field_index.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/release_bundle_manifest.json": ("validate_outputs", "validate_manuscript"),
    "output/data/theorem_traceability_matrix.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/artifact_diffoscope.json": ("validate_outputs", "validate_manuscript"),
    "output/data/proof_extraction_index.json": ("validate_outputs", "validate_manuscript"),
    "output/data/state_space_catalog.json": ("validate_outputs", "validate_manuscript"),
    "output/data/causal_ablation_matrix.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/artifact_license_audit.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/release_notes_evidence.json": ("validate_outputs", "validate_manuscript"),
    "output/data/scholarship_source_matrix.json": ("validate_outputs", "validate_manuscript"),
    "output/figures/scholarship_source_map.png": ("validate_outputs", "figure_registry"),
    "output/data/firstprinciples/correspondence_map.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/opd_taxonomy.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/divergence_demo.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/reward_tilting_demo.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/exposure_bias_demo.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/sdpg_demo.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/correspondence_table.md": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/taxonomy_table.md": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/statistics_demo.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/empirical_benchmark.json": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/benchmark_table.md": ("validate_outputs", "validate_manuscript"),
    "output/data/firstprinciples/classroom.json": ("validate_outputs", "validate_manuscript"),
    "output/data/proof_dependency_graph.json": ("validate_outputs", "validate_manuscript"),
    "output/data/state_transition_table.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/ablation_sensitivity_report.json": ("validate_outputs", "validate_manuscript"),
    "output/reports/release_attestation.json": ("validate_outputs", "validate_manuscript"),
}


__all__ = [
    "ARTIFACT_CONSUMERS",
    "ARTIFACT_GATES",
    "ARTIFACT_PRODUCERS",
    "DEFAULT_ANALYSIS_SCRIPTS",
    "REQUIRED_OUTPUT_CHECK_KEYS",
    "REQUIRED_OUTPUTS",
    "SEMANTIC_SCHEMA",
    "ScriptStep",
]
